name: Automatically publish to Modrinth
on:
  release:
    types: [published]
jobs:
  publish-to-modrinth:
    if: github.repository_owner == 'topnotchfoxy'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: github-actions
    permissions:
      attestations: write
      artifact-metadata: write
      contents: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"
          java-package: "jre"
      - name: Build Pack
        run: |
          pushd Pakku/
          MC_VERSION=$(jq -r '.mc_versions[0]' pakku-lock.json)
          echo "MC_VERSION=$MC_VERSION" >> $GITHUB_ENV
          PACK_VERSION=$(jq -r '.version' pakku.json)
          echo "PACK_VERSION=$PACK_VERSION" >> $GITHUB_ENV
          PACK_NAME=$(jq -r '.name' pakku.json)
          echo "PACK_NAME=$PACK_NAME" >> $GITHUB_ENV
          wget https://github.com/juraj-hrivnak/Pakku/releases/latest/download/pakku.jar
          java -jar pakku.jar export --no-server
          popd
      - name: Publish to Modrinth
        uses: Kira-NT/mc-publish@v3.3
        with:
          name: MC${{ env.MC_VERSION }}-${{ env.PACK_VERSION }}
          modrinth-id: Er2bMzL7
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: ./Pakku/build/modrinth/*.mrpack
          loaders: fabric
          game-versions: ${{ env.MC_VERSION }}
          version: MC${{ env.MC_VERSION }}-${{ env.PACK_VERSION }}
      - name: Upload to Github Release
        uses: softprops/action-gh-release@v3
        with:
          files: ./Pakku/build/modrinth/*.mrpack